r"""
Uncorrelated Statistical Model Combiner
=======================================

This module provides :class:`UncorrelatedStatisticsCombiner`, a ``spey`` **plug-in**
(``default.uncorrelated_combiner``) that combines an arbitrary collection of
:class:`~spey.StatisticalModel` objects under the assumption that they are
statistically **independent** (uncorrelated): the analyses share their parameter of
interest :math:`\mu`, and nothing else.

It is the simplest specialisation of
:class:`~spey.combiner.combiner_core.CombinerBase` — the parameter of interest of
every constituent model is mapped onto one global slot, and every other parameter
keeps a private slot.  The general machinery (likelihood, gradient, Hessian, Asimov
data, sampling) is described in :mod:`spey.combiner.combiner_core`.

Mathematical Background
-----------------------

**Factorised likelihood**

Given :math:`N` independent statistical models indexed by :math:`i`, each with its
own set of nuisance parameters :math:`\boldsymbol{\theta}_i`, the joint likelihood is

.. math::

    \mathcal{L}_{\rm comb}(\mu, \{\boldsymbol{\theta}_i\})
    = \prod_{i=1}^{N} \mathcal{L}_i(\mu, \boldsymbol{\theta}_i),

where :math:`\mu` is the single, shared parameter of interest (signal strength).
Taking the negative logarithm converts the product into a sum,

.. math::

    -\ln\mathcal{L}_{\rm comb}(\mu, \{\boldsymbol{\theta}_i\})
    = \sum_{i=1}^{N} \left[-\ln\mathcal{L}_i(\mu, \boldsymbol{\theta}_i)\right].

**Profile likelihood**

Because no nuisance parameter is shared, the conditional maximum at fixed :math:`\mu`
decouples into independent fits, :math:`\hat{\hat{\boldsymbol{\theta}}}_i(\mu)`, and
the combined profile negative log-likelihood is the sum of the individual ones,

.. math::

    -\ln\mathcal{L}_{\rm comb}\!\left(\mu, \hat{\hat{\boldsymbol{\theta}}}(\mu)\right)
    = \sum_{i=1}^{N}
      -\ln\mathcal{L}_i\!\left(\mu, \hat{\hat{\boldsymbol{\theta}}}_i(\mu)\right).

The combination is therefore exact.  It is evaluated as a single joint fit over
:math:`(\mu, \boldsymbol{\theta}_1, \dots, \boldsymbol{\theta}_N)` using the
gradients and Hessians supplied by the constituent backends, which is equivalent to
profiling each model separately but lets the optimiser use analytic derivatives, and
gives access to :func:`~spey.StatisticalModel.sigma_mu_from_hessian`, the toy
calculator, and :func:`~spey.multiparameter.find_contour`.

**Asimov data**

Asimov data are generated by the combined model: at fixed :math:`\mu` the joint
nuisance-parameter fit decouples, so the result coincides with generating the Asimov
data of every constituent model independently.  The combined dataset is laid out in
model order; :func:`~spey.combiner.combiner_core.CombinerBase.split_data` recovers
the per-analysis pieces.

.. versionadded:: 0.2.8

    Replaces :class:`~spey.UnCorrStatisticsCombiner`, which is deprecated.

References
----------
* G. Cowan, K. Cranmer, E. Gross, O. Vitells, *Asymptotic formulae for
  likelihood-based tests of new physics*, Eur. Phys. J. C **71** (2011) 1554,
  :xref:`1007.1727`.
"""

from typing import Dict, List, Sequence, Tuple

import numpy as np

from spey.interface.statistical_model import StatisticalModel
from spey.system.exceptions import InvalidInput

from .combiner_core import CombinerBase

__all__ = ["UncorrelatedStatisticsCombiner"]


def __dir__():
    return __all__


def __getattr__(name: str):
    # Backwards compatibility: the deprecated class used to live in this module.
    if name == "UnCorrStatisticsCombiner":
        from .deprecated_combiner import (  # pylint: disable=import-outside-toplevel
            UnCorrStatisticsCombiner,
        )

        return UnCorrStatisticsCombiner
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


class UncorrelatedStatisticsCombiner(CombinerBase):
    r"""
    Combine **uncorrelated** (independent) statistical models
    (``default.uncorrelated_combiner``).

    The constituent models share their parameter of interest :math:`\mu` and nothing
    else, so the joint likelihood factorises into a product of individual likelihoods,

    .. math::

        \mathcal{L}_{\rm comb}(\mu, \{\boldsymbol{\theta}_i\})
        = \prod_{i} \mathcal{L}_i(\mu, \boldsymbol{\theta}_i).

    The constituent models are not required to use the same backend — any mix of
    registered backends is supported.  The combined parameter vector holds the shared
    POI at index ``0`` followed by the private parameters of every model, in model
    order; :attr:`~spey.combiner.combiner_core.CombinerBase.index_map` shows where
    each local parameter lives.

    .. warning::

        This combiner assumes that **none** of the constituent statistical models
        share nuisance parameters.  Violating this assumption leads to incorrect
        (over-confident) results because the nuisance parameters of each model are
        treated as independent.  Use
        :class:`~spey.combiner.CorrelatedStatisticsCombiner`
        (``default.correlated_combiner``) to identify shared nuisance parameters.

    Args:
        statistical_models (``Sequence[~spey.StatisticalModel]``): Independent models
          to combine.  Their :attr:`~spey.StatisticalModel.analysis` identifiers must
          be unique.

    Raises:
        ``TypeError``: If an entry of ``statistical_models`` is not a
          :class:`~spey.StatisticalModel`.
        ``~spey.system.exceptions.AnalysisQueryError``: If two models share the same
          :attr:`~spey.StatisticalModel.analysis` identifier.
        ``~spey.system.exceptions.InvalidInput``: If ``statistical_models`` is empty,
          if a model does not declare a parameter of interest, or if the POI bounds of
          the models do not overlap.

    Example:

    .. code-block:: python3

        >>> import spey

        >>> poisson = spey.get_backend("default.poisson")
        >>> model_a = poisson(
        ...     signal_yields=[3.0], background_yields=[50.0], data=[52], analysis="SR_A"
        ... )
        >>> model_b = poisson(
        ...     signal_yields=[1.5], background_yields=[20.0], data=[18], analysis="SR_B"
        ... )

        >>> combiner = spey.get_backend("default.uncorrelated_combiner")
        >>> combined = combiner(statistical_models=[model_a, model_b], analysis="SR_A+SR_B")
        >>> combined.exclusion_confidence_level()  # combined CLs
        >>> combined.poi_upper_limit()

    .. seealso::

        :class:`~spey.combiner.CorrelatedStatisticsCombiner` for combining models that
        share nuisance parameters as well.
    """

    name: str = "default.uncorrelated_combiner"
    """Name of the backend"""

    __slots__ = []

    def __init__(self, statistical_models: Sequence[StatisticalModel]):
        super().__init__(statistical_models)

    def _build_parameter_map(
        self, local_names: List[List[str]]
    ) -> Tuple[List[np.ndarray], Dict[int, str]]:
        """
        Map the parameter of interest of every model onto one shared slot.

        The shared slot is named after the POI of the first model (``"mu"`` unless its
        backend declares otherwise); all other parameters stay private.

        Args:
            local_names (``List[List[str]]``): Local parameter names per model.

        Raises:
            ``~spey.system.exceptions.InvalidInput``: If a model does not declare a
              parameter of interest.

        Returns:
            ``Tuple[List[np.ndarray], Dict[int, str]]``:
            Gather map of every model and the name of the shared POI slot.
        """
        group_of = {}
        for pos, (cfg, model) in enumerate(zip(self._configs, self._models)):
            if cfg.poi_index is None:
                raise InvalidInput(
                    f"'{model.analysis}' does not declare a parameter of interest and "
                    "can not be combined."
                )
            group_of[(pos, cfg.poi_index)] = "poi"

        maps, slot_of_group = self._allocate_slots(local_names, group_of)
        poi_name = local_names[0][self._configs[0].poi_index]
        return maps, {slot_of_group["poi"]: poi_name}

    def combine(
        self, other: "UncorrelatedStatisticsCombiner", **kwargs
    ) -> "UncorrelatedStatisticsCombiner":
        """
        Merge two uncorrelated combinations into one.

        Enables the ``@`` operator between two models built from this backend:
        ``combined = combined_ab @ combined_cd``.

        Args:
            other (:class:`UncorrelatedStatisticsCombiner`): Backend of the other
              combination.
            kwargs: Unused.

        Raises:
            ``TypeError``: If ``other`` is not an :class:`UncorrelatedStatisticsCombiner`;
              to add a single model, build a new combination from
              ``[*combined.backend.statistical_models, model]``.
            ``~spey.system.exceptions.AnalysisQueryError``: If both combinations contain
              the same analysis.

        Returns:
            :class:`UncorrelatedStatisticsCombiner`:
            Combination of the models of both operands, ``self``'s first.
        """
        if not isinstance(other, UncorrelatedStatisticsCombiner):
            raise TypeError(
                f"Can not combine {type(self).__name__} with {type(other).__name__}. "
                "To add a single model, build a new combination from "
                "`[*combined.backend.statistical_models, model]`."
            )
        return UncorrelatedStatisticsCombiner([*self._models, *other.statistical_models])
