name: Lint

on:
  push:
    branches:
      - release/*
  # Each pull request should be validated before merging with main or dev
  pull_request:
    branches:
      - main
      - dev
  # Enables manual action execution.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write

jobs:
  lint:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        id: action_black
        with:
          options: "-l 100"
          src: "./src"
    #   - name: Create Pull Request
    #     if: steps.action_black.outputs.is_formatted == 'true'
    #     uses: peter-evans/create-pull-request@v3
    #     with:
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #       title: "Format Python code with psf/black push"
    #       commit-message: ":art: Format Python code with psf/black"
    #       body: |
    #         There appear to be some python formatting errors in ${{ github.sha }}. This pull request
    #         uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
    #       base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
    #       branch: actions/black
