on:
  pull_request:
    branches: ["main", "releases/**"]
  push:
    branches: ["main", "releases/**", "testing"]

name: Check if pre-commit checks pass

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v3.0.1
